VERSION="2.2.1"

ACCOUNTS=[
"XXX",
]

[DOCUMENTATION]
ORG_NAME="UnitedHealth Group"
ORG_URL="https://stellarunited.digital/"
ORG_DESCRIPTION="We are a global team of health and wellness professionals working to create an advanced, effective healthcare system."
ORG_LOGO="https://stellarunited.digital/logo.png"
ORG_OFFICIAL_EMAIL="stellaruhg@gmail.com"


[[CURRENCIES]]
code="UHG"
status="live"
display_decimals=2
issuer="XXX"
anchor_asset_type="crypto"
name="UnitedHealth Group"
desc="We are a global team of health and wellness professionals working to create an advanced, effective healthcare system."
image="https://stellarunited.digital/logo.png"
fixed_number=100000000
max_number=100000000
is_unlimited=false
#UnitedHealth Group was issued using the open and inclusive Stellar blockchain network.
