VERSION="2.2.1"

ACCOUNTS=[
"XXX",
]

[DOCUMENTATION]
ORG_NAME="UnitedHealth Group"
ORG_URL="XXX"
ORG_DESCRIPTION=""
ORG_LOGO="XXX"
ORG_OFFICIAL_EMAIL="stellaruhg@gmail.com"


[[CURRENCIES]]
code="XXX"
status="live"
display_decimals=2
issuer="XXX"
anchor_asset_type="crypto"
name="UnitedHealth Group"
desc="XXX"
image="XXX"
fixed_number=100000000
max_number=100000000
is_unlimited=false
#UnitedHealth Group was issued using the open and inclusive Stellar blockchain network.
